name: build_example

on:
  push:

jobs:       
  build_example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup node.js
        uses: actions/setup-node@v4
        with: 
          node-version:  '20'
      - name: Verify files
        run: ls -alhR
      - name: bundle code into a zip
        run: npm install
      - name: bundle code into zip
        run: zip -r app.bundle.zip . -x "*.git*" 
      - name: Better Test Reports Action
        uses: mridang/action-test-reporter@v1.7.0
        with: 
          skip-coverage: true