name: dependencies Example

on:
  workflow_dispatch:
  push:

jobs:
  dependencies_example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
      - name: Verify files
        run: ls -alhR

        
  build_example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup node.js
        uses: setup-node@v4
        with: 
          node-version:  '20'
      - name: bundle code into a zip
        run: 
          npm install
          zip -r app.bundle.zip . -x "*.git*" 
